apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fau-monitor.fullname" . }}
  labels:
    {{- include "fau-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fau-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fau-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6123
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/status
              port: 6123
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: 6123
            initialDelaySeconds: 5
            periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAntiAffinity }}
      affinity:
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.podAffinity }}
      affinity:
        podAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
