apiVersion: v1
kind: Secret
metadata:
  name: faumon-config-secrets
type: Opaque
stringData:
    "config.json": |
        {
          "refresh_interval_seconds": 60,
          "group_priority": {
            "DATA CENTERS": 100,
            "INFRASTRUCTURE": 90,
            "ATHENE": 80,
            "AS APPS - PRODUCTION": 70,
            "IAM APPS": 60,
            "ACADEMIC NETWORKS": 50,
            "COLDFUSION": 40,
            "MYPOS": 30,
            "OWL CLOUD": 20,
            "Radiator": 10
          },
          "endpoints": [
            {
              "url": "https://entappmon.fau.edu/api/v1/endpoints/statuses",
              "verify_ssl": true
            },
            {
              "url": "https://gatus.hpc.fau.edu/api/v1/endpoints/statuses",
              "verify_ssl": false
            },
            {
              "url": "https://librenmstogatos.hpc.fau.edu/health?ids=106,107,108,109,110,117,130,132,133,137,138,14,140,142,143,144,146,147,148,149,151,154,155,156,157,158,159,16,160,163,164,165,175,176,177,18,20,21,22,23,24,263,264,273,278,28,29,30,31,32,33,356,357,358,359,360,362,363,364,365,366,367,369,37,373,374,375,376,377,38,39,396,397,398,399,40,400,401,402,403,404,405,406,407,408,409,41,411,413,414,415,418,42,420,421,422,424,43,44,440,443,444,446,447,448,45,454,457,458,459,46,460,461,462,464,465,466,467,468,469,47,470,471,472,473,475,48,483,485,487,49,498,50,508,51,52,53,532,55,56,560,563,564,57,577,58,587,59,599,60,600,602,603,604,605,61,63,64,65,67,69,70,71,72,725,73,75,76,79,98",
              "verify_ssl": false
            },
            {
              "url": "https://temperature.hpc.fau.edu/metrics",
              "type": "prometheus",
              "verify_ssl": false
            },
            {
              "url": "https://librenmstogatos.hpc.fau.edu/metrics",
              "verify_ssl": false,
              "type": "prometheus"
            }
          ],
          "filters": {
            "exclude": [
              "*test*",
              "*dev*"
            ],
            "include": [
              {
                "pattern": "*crystalreports*",
                "group": "Reporting Services"
              },
              {
                "pattern": "*canvas*",
                "group": "Academic Applications"
              },
              {
                "pattern": "*radiator*",
                "group": "Radiator"
              }
            ]
          },
          "default_group_contacts": {
            "Radiator T": {
              "name": "Wifi Support Team",
              "phones": [
                "+1-561-289-8179 (Rhian)",
                "+1-561-555-0112 (Greg)"
              ],
              "emails": [
                "security@fau.edu",
                "hpc@fau.edu"
              ]
            },
            "Reporting Services": {
              "name": "Reporting Services Support Team",
              "phones": [
                "+1-561-555-0111",
                "+1-561-555-0112"
              ],
              "emails": [
                "reports-help@fau.edu",
                "reports-escalations@fau.edu"
              ]
            },
            "Radiator": {
              "name": "Infrastructure Services Support Team",
              "phones": [
                "+1-561-555-0111",
                "+1-561-555-0112"
              ],
              "emails": [
                "hpc@fau.edu",
                "networking@fau.edu"
              ]
            },
            "Academic Applications": {
              "name": "Academic Tech On-Call Group",
              "phones": [
                "+1-561-555-0222"
              ],
              "emails": [
                "acadtech@fau.edu",
                "canvas-admin@fau.edu"
              ]
            },
            "General": {
              "name": "OIT Central Helpdesk",
              "phones": [
                "+1-561-555-0100",
                "+1-561-555-0101"
              ],
              "emails": [
                "helpdesk@fau.edu"
              ]
            }
          },
          "service_contacts": {
            "as-apps---production_crystalreports": {
              "name": "Crystal Reports Lead Specialist",
              "phones": [
                "+1-561-555-0999",
                "+1-561-555-0998"
              ],
              "emails": [
                "crystal-lead@fau.edu",
                "crystal-backup@fau.edu"
              ]
            }
          }
        }